Neste exercício você deve preencher os códigos necessários para cada etapa


# Importe as principais bibliotecas que irá usar
os, opencv, matplotlib, numpy

In [1]:
#blibliotecas

%matplotlib inline 
import os
import cv2
import matplotlib.pyplot as plt 
import numpy as np


# Extração de Features

Vamos criar uma função que retorne um array de características da imagem.  
Serão 4 características: 
* percentual de pixels com valor acima 230 de do canal R do espaço de cor RGB 
* percentual de pixels com valor acima 230 de do canal G do espaço de cor RGB 
* percentual de pixels com valor acima 125 de do canal Cr do espaço de cor YCrCb 
* percentual de pixels com valor acima 125 de do canal Cb do espaço de cor YCrCb

Exemplo de retorno: 
> [ 0.05094044      0.02194357      0.              0.04153605]


In [2]:
def featureExtract(imagem):
    
    # informe aqui o código
    
    countR = cv2.calcHist([imagem],[0],None,[10],[0,256])
    countG = cv2.calcHist([imagem],[1],None,[10],[0,256])
    
    imgYCrCb = cv2.cvtColor(img, cv2.COLOR_RGB2YCR_CB)
   
    countR2 = cv2.calcHist([imgYCrCb],[1],None,[2],[0,256])
    countG2 = cv2.calcHist([imgYCrCb],[2],None,[2],[0,256])    
    
    pixels = (imagem.shape[0] * imagem.shape[1])
    
    percR = countR[-1:]/pixels
    percG = countG[-1:]/pixels
    percCr = countR2[-1:]/pixels
    percCb = countG2[-1:]/pixels
    
    return (np.concatenate((percR,percG,percCr,percCb),axis=0).reshape(-1))

# Leia o database de sinaleiras, conforme na tarefa 6
A diferença está na informação armazenada em ListaX, na tarefa 6 é armazenado todos os pixels da imagem, neste exercício, vamos armazenar apenas o retorno da função ** featureExtract(imagem) ** 

Exemplo de retorno para 4 imagens:
> [ 0.01465201  0.31868133  0.24267399  0.00641026]  
> [ 0.          0.00172414  0.05689655  0.69482756]  
> [ 0.01061224  0.06857143  0.20816326  0.20897959]  
> [ 0.01400181  0.02619693  0.22899729  0.58039749]  


In [3]:
listaX = []
listaY = []

# informe aqui o código

path_0 = "../images/0/"
path_1 = "../images/1/"

for filename in os.listdir(path_0):
    img = cv2.imread(os.path.join(path_0, filename))
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    listaX.append(featureExtract(imgRGB))
    listaY.append(0)
    
for filename in os.listdir(path_1):
    img = cv2.imread(os.path.join(path_1, filename))
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    listaX.append(featureExtract(imgRGB))
    listaY.append(1)
    


  # Separe em dados de treino e testes
  ## quantidade de testes = 33% 
  
  X_train, X_test, y_train, y_test
  
  utilizando ** train_test_split **

In [4]:
# informe aqui o código

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( listaX, listaY, test_size=0.33)


O retorno da dos comandos deve ser: 
> (402, 4)  
> (402,)  
> (198, 4)  
> (198,)  

In [5]:
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(402, 4)
(402,)
(198, 4)
(198,)


# Faça o treinamento com SVM


In [6]:
# informe aqui o código

from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

# Faça a predição

In [7]:
# informe aqui o código

predictions = model.predict(X_test)


# Mostre a matriz de confusão e as medidas de avaliação
utilizando: ** classification_report e confusion_matrix **

In [8]:
# informe aqui o código

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[ 50  21]
 [  9 118]]
             precision    recall  f1-score   support

          0       0.85      0.70      0.77        71
          1       0.85      0.93      0.89       127

avg / total       0.85      0.85      0.84       198



# Faça o cross-validation para encontrar os melhores parâmatros para o SVM
utilizando ** GridSearchCV **

In [9]:
# informe aqui o código

from sklearn.model_selection import GridSearchCV
param_grid = {'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,verbose=1)
grid.fit(X_train, y_train)

Fitting 3 folds for each of 25 candidates, totalling 75 fits


[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:    0.3s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=1)

# Faça a predição novamente, agora com os novos parâmetros selecionados

In [10]:
# informe aqui o código

grid_predictions = grid.predict(X_test)

# Mostre a matriz de confusão e as medidas de avaliação

In [11]:
# informe aqui o código

print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test,grid_predictions))

[[ 69   2]
 [  0 127]]
             precision    recall  f1-score   support

          0       1.00      0.97      0.99        71
          1       0.98      1.00      0.99       127

avg / total       0.99      0.99      0.99       198

